"""create_videos_and_detections

Revision ID: 33e660f5b636
Revises: 
Create Date: 2026-06-05 16:19:29.046403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '33e660f5b636'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # POSTGRESQL'E VECTOR EKLENTİSİNİ KUR (pgvector için zorunlu)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('object_class', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_anomaly', sa.Enum('NIGHT_INTRUSION', 'RESTRICTED_ZONE', 'ABANDONED_OBJECT', 'SUSPICIOUS_LOITERING', 'NONE', name='anomalytype'), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('videos')
    
    # PostgreSQL'de Enum tipleri tablo silinse bile kalır. Temiz bir downgrade için bunu da siliyoruz:
    op.execute("DROP TYPE IF EXISTS anomalytype")
    # ### end Alembic commands ###